language: cpp
gcc:
  - "4.9"
dist: trusty
sudo: required
cache:
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - |
    sudo apt-get install libfreetype6-dev libboost-date-time-dev libois-dev libluajit-5.1-dev libboost-thread-dev nvidia-cg-toolkit libfreeimage-dev zlib1g-dev libzzip-dev libcppunit-dev doxygen libxt-dev libxaw7-dev libxxf86vm-dev libxrandr-dev libglu-dev libboost-dev cmake libx11-dev g++ libjsoncpp-dev
  - git clone https://github.com/msgpack/msgpack-c.git
  - cd msgpack-c && cmake . && make && sudo make install && cd ..
script:
  - mkdir build && cd build && cmake .. && cmake --build . && cd bin && ./unit-tests --gtest_output=xml:TestResults.xml
