language: cpp
matrix:
  include:
    - compiler: gcc
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            # install toolchains
            - xvfb
            - gcc-4.9
            - g++-4.9
            - cmake
            - clang-3.6
            - libglu-dev
            - libois-dev
            - python-dev
            - libxt-dev
            - libxaw7-dev
            - libxrandr-dev
            - libglu-dev
            - libglew-dev

    - compiler: clang
      os: osx
      osx_image: xcode7.3
      env:
        - OGRE_ENABLED=0

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew --universal ; fi
  - export DISPLAY=:99.0
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
  - sleep 3

install:
  - sudo pip install conan
  - make build
script:
  - make ci
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ec885fc0b74db2feac0
    on_success: change
    on_failure: always
    on_start: never
