# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\gsage

platform: x64
configuration: RelWithDebInfo

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe

# scripts to run before build
before_build:
  - c:\MinGW\bin\mingw32-make.exe build

# scripts to run after build
test_script:
  - c:\MinGW\bin\mingw32-make.exe test

# scripts to run after build
after_build:
  - cd c:\projects\gsage\build
  - 7z a c:\projects\gsage.zip * -tzip
  - cd c:\projects\gsage

artifacts:
  - path: gsage.zip
    name: gsage.zip
