# Operating system (build VM template)
os: Visual Studio 2017

# clone directory
clone_folder: c:\projects\gsage

platform: x64
configuration: Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan remote add gsage https://api.bintray.com/conan/gsage/main --insert && conan user -p 3d14168da7de2092522ed90f72e9b6bf20db89e5 -r gsage gsage-ci

# scripts to run before build
before_build:
  - conan install -g cmake -o gsage:with_ogre=1.9.0 -o gsage:with_input=OIS -o gsage:with_librocket=True -o with_lua_version=luajit-2.0.5 --build=outdated .
  - conan upload "*" --all -r gsage -c

build_script:
  - conan build .
  - cd build && cmake ..


# scripts to run after build
test_script:
  - cd ./build/bin/ && unit-tests.exe

# scripts to run after build
after_build:
  - cd c:\projects\gsage\build
  - 7z a c:\projects\gsage.zip * -tzip
  - cd c:\projects\gsage

artifacts:
  - path: gsage.zip
    name: gsage.zip
